### ISSUE TITLE
4.19 failed to generate project files

### ISSUE THREAD

**Issue by mitjaprelovsek** [AleDel/Spout-UE4#37]
Hi,

I am having a bit of a problem making this work in 4.19. After trying to open a project it says that it cannot compile spout dll's and after trying to recompile it says I should try to compile from source manually.

After I try to generate project files it says:

`Running E:/unrealEngine/UE_4.19/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="H:/projectSandbox/spout4UE4/cppFPSSpout/cppFPSSpout.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
While compiling H:\projectSandbox\spout4UE4\cppFPSSpout\Intermediate\Build\BuildRules\cppFPSSpoutModuleRules.dll:
ERROR: h:\projectSandbox\spout4UE4\cppFPSSpout\Plugins\SpoutUE4\Source\SpoutPlugin\SpoutPlugin.Build.cs(20,9) : error CS1729: 'UnrealBuildTool.ModuleRules' does not contain a constructor that takes 0 arguments
WARNING: h:\projectSandbox\spout4UE4\cppFPSSpout\Plugins\SpoutUE4\Source\SpoutPlugin\SpoutPlugin.Build.cs(92,13) : warning CS0618: 'UnrealBuildTool.ModuleRules.RuntimeDependencyList.Add(UnrealBuildTool.ModuleRules.RuntimeDependency)' is obsolete: 'Constructing a RuntimeDependency object is deprecated. Call RuntimeDependencies.Add() with the path to the file to stage.'
ERROR: UnrealBuildTool Exception: Unable to compile source files.`

**Comment by mitjaprelovsek** [comment]
Ok, I found the issue based on [this page](https://answers.unrealengine.com/questions/764146/unreal-build-tool-error-1.html).

You have to change line 20 in SpoutPlugin.Build.cs from:
`public SpoutPlugin(TargetInfo Target)`

to:
`public SpoutPlugin(ReadOnlyTargetRules Target) : base(Target)`

I got the project to compile and open now.
